name: quiz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.2.4
  flutter_svg: ^2.0.10+1
  flutter_tex: ^4.0.3+4
  google_fonts: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.19.0
  lottie: ^2.6.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  wakelock: ^0.4.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
